# Generated by Django 5.2.6 on 2025-09-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='numero_de_orden',
            field=models.IntegerField(default=0),
        ),
    ]
