# Generated by Django 5.2.7 on 2025-10-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_descripcion_producto_numero_de_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripción'),
        ),
    ]
